import React from 'react';
import { motion } from 'framer-motion';
import Container from '../components/common/Container';
import PageHero from '../components/common/PageHero';
import SectionHeading from '../components/common/SectionHeading';
import Button from '../components/common/Button';
import { opexSteps } from '../data/services';
import { fadeUp, staggerContainer, fadeLeft, fadeRight } from '../utils/animations';
import {
  Zap,
  ArrowRight,
  CheckCircle,
  ShieldCheck,
  TrendingDown,
  Clock,
  Sparkles,
  Check,
  Building,
  CheckCircle2,
} from 'lucide-react';

export default function RooftopOPEX({ onNavigate }) {
  const comparisonMetrics = [
    {
      metric: 'Investment Burden',
      status: 'ZERO (₹0 Capital Outlay)',
      description: 'Volga funds 100% of engineering, procurement, BOS, and installation costs.',
      tone: 'emerald',
    },
    {
      metric: 'Operational Responsibility',
      status: 'NONE (100% Volga Managed)',
      description: 'Zero maintenance overhead, insurance liability, or spare parts risk for your business.',
      tone: 'secondary',
    },
    {
      metric: 'Energy Savings',
      status: 'IMMEDIATE (Day 1 Tariff Reduction)',
      description: 'Instantly buy clean solar power at tariffs 25% to 45% cheaper than state electricity boards.',
      tone: 'primary',
    },
  ];

  const benefits = [
    {
      title: 'No Upfront Investment',
      desc: 'Preserve your company’s precious capital reserves and debt lines for your primary core business operations.',
      icon: TrendingDown,
    },
    {
      title: 'Immediate Electricity Savings',
      desc: 'Experience immediate operational expenditure reductions on your utility power bills from the day of commissioning.',
      icon: Zap,
    },
    {
      title: 'Zero Maintenance Responsibility',
      desc: 'Volga’s certified O&M technicians manage all preventive cleaning, inverter repairs, panel health, and spare parts.',
      icon: ShieldCheck,
    },
    {
      title: 'Predictable Energy Costs',
      desc: 'Lock in a fixed or index-hedged PPA tariff for 15 to 25 years, shielding your facility from unpredictable utility hikes.',
      icon: Clock,
    },
  ];

  return (
    <div className="flex flex-col min-h-screen">
      {/* Page Hero */}
      <PageHero
        title="Rooftop Solar – OPEX Model"
        highlight="OPEX Model"
        description="The OPEX model allows businesses to adopt solar power without investing capital in the solar installation. Volga Solar Solutions installs and owns the solar plant while the customer purchases electricity generated by the system."
        onNavigate={onNavigate}
      />

      {/* Visual Comparison Section (Investment Burden vs Responsibility vs Savings) */}
      <section className="py-20 bg-neutral-50 text-heading relative overflow-hidden border-b border-border">
        <Container className="relative z-10">
          <div className="text-center max-w-2xl mx-auto mb-12">
            <h2 className="text-2xl sm:text-4xl font-extrabold text-heading">
              Effortless Green Transition
            </h2>
            <p className="text-body mt-2 text-sm sm:text-base">
              Experience the financial upside of renewable power without operational distraction or balance sheet commitment.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-5xl mx-auto">
            {comparisonMetrics.map((item, i) => (
              <motion.div
                key={item.metric}
                variants={fadeUp}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                transition={{ delay: i * 0.15 }}
                className="p-8 rounded-3xl bg-white border border-border shadow-subtle relative overflow-hidden flex flex-col justify-between group hover:border-secondary/40 transition-colors"
              >
                <div>
                  <div className="text-xs font-mono font-bold tracking-wider text-muted uppercase mb-2">
                    Key Dimension 0{i + 1}
                  </div>
                  <h3 className="text-lg font-bold text-heading mb-4">
                    {item.metric}
                  </h3>
                  <div className="p-3 rounded-xl bg-secondary-light border border-secondary/20 text-secondary font-black text-sm font-mono tracking-tight">
                    {item.status}
                  </div>
                  <p className="mt-4 text-xs sm:text-sm text-body leading-relaxed">
                    {item.description}
                  </p>
                </div>
                <div className="mt-6 pt-4 border-t border-border flex items-center gap-2 text-xs text-emerald-600 font-semibold">
                  <CheckCircle2 className="w-4 h-4 shrink-0" />
                  <span>Risk-Free Guarantee</span>
                </div>
              </motion.div>
            ))}
          </div>
        </Container>
      </section>

      {/* How It Works (Three-Step Visual) */}
      <section className="py-24 bg-white relative">
        <Container>
          <SectionHeading
            badge="Simple 3-Step Process"
            title="How the OPEX Model Works"
            highlight="OPEX Model"
            subtitle="From site assessment to daily green energy delivery, we manage the full lifecycle complexity."
            align="center"
            className="mb-16"
          />

          <motion.div
            variants={staggerContainer(0.15, 0.1)}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-60px' }}
            className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto"
          >
            {opexSteps.map((step, idx) => (
              <motion.div
                key={step.step}
                variants={fadeUp}
                whileHover={{ y: -6 }}
                className="p-8 rounded-3xl bg-neutral-50 border border-border relative flex flex-col justify-between group hover:shadow-elevated transition-all"
              >
                <div>
                  <div className="flex items-center justify-between mb-6">
                    <span className="text-4xl font-black font-mono text-secondary-dark">
                      {step.step}
                    </span>
                    <span className="text-xs font-bold uppercase tracking-wider text-muted bg-white px-2.5 py-1 rounded-full border border-border">
                      Stage {step.step}
                    </span>
                  </div>

                  <h3 className="text-xl font-bold text-heading group-hover:text-secondary-dark transition-colors">
                    {step.title}
                  </h3>

                  <p className="mt-3 text-sm text-body leading-relaxed">
                    {step.desc}
                  </p>
                </div>

                <div className="mt-8 pt-4 border-t border-neutral-200/60 flex items-center gap-2 text-xs font-semibold text-secondary-dark">
                  <Check className="w-4 h-4" />
                  <span>Volga Full Accountability</span>
                </div>
              </motion.div>
            ))}
          </motion.div>
        </Container>
      </section>

      {/* Benefits Breakdown */}
      <section className="py-24 bg-background relative border-t border-border">
        <Container>
          <SectionHeading
            badge="Strategic Value"
            title="Key Benefits of Volga OPEX Solar"
            highlight="Key Benefits"
            subtitle="Delivering instant operational cost savings without capital risk or technical complexity."
            align="center"
            className="mb-16"
          />

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {benefits.map((b) => {
              const Icon = b.icon;
              return (
                <div
                  key={b.title}
                  className="p-6 rounded-2xl bg-surface border border-border shadow-subtle hover:shadow-elevated transition-all flex flex-col justify-between group"
                >
                  <div>
                    <div className="w-12 h-12 rounded-xl bg-secondary-light text-secondary-dark flex items-center justify-center mb-5 group-hover:bg-secondary group-hover:text-dark transition-colors">
                      <Icon className="w-6 h-6" />
                    </div>
                    <h3 className="text-lg font-bold text-heading group-hover:text-secondary-dark transition-colors">
                      {b.title}
                    </h3>
                    <p className="mt-2.5 text-sm text-body leading-relaxed">
                      {b.desc}
                    </p>
                  </div>
                  <div className="mt-6 pt-4 border-t border-neutral-100 flex items-center gap-1.5 text-xs font-semibold text-emerald-600">
                    <Check className="w-4 h-4" />
                    <span>Immediate Financial Impact</span>
                  </div>
                </div>
              );
            })}
          </div>
        </Container>
      </section>

    </div>
  );
}
